stages:
  - deploy

deploy:
  stage: deploy
  image:
    name: registry.gitlab.com/pipeline-components/deployer:latest
    entrypoint: [""]
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
    - dep deploy -vvv
    - sh notify.sh "success message 🚀"
  resource_group: production
  only:
    - main

notify_error:
  stage: notify
  script:
    - sh notify.sh "fail message ❌"
  when: on_failure
